config/routes.rb
Rails.application.routes.draw do
  resources :managestudents

  resources :student_quizzes
  get 'all_students',to: 'student_quizzes#all_students'
  get 'assign_quiz', to: 'student_quizzes#assign_quiz'
  resources :class_names do
    resources :module_names do
      resources :levels 
    end
  end

  get 'set_module_name', to: 'students#set_module_name', :defaults => { :format => 'js' }
  get 'set_level', to: 'students#set_level', :defaults => { :format => 'js' }
  get 'set_quiz', to: 'students#set_quiz', :defaults => { :format => 'js' }
  get 'set_type_of_quiz', to: 'students#set_type_of_quiz', :defaults => { :format => 'js' }

  # resources :module_names
  # resources :levels
  # resources :class_names

  resources :image_uploads
  resources :questions
  resources :type_of_quizzes
  resources :quizzes
  get 'home', to: 'static_pages#home'
  get 'teacher', to: 'static_pages#show'

  get 'upload_detail', to: 'static_pages#upload_detail'

  get 'activate_quiz', to: 'quizzes#activate_quiz'
  
  root 'static_pages#home'
  # root 'devise/sessions#new'
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  
  
  devise_for :views
  # devise_for :users
  get 'create_question',to: 'questions#create_question'
  post 'update_question', to:"questions#update_question"
  get 'students',to: 'students#index'
  get 'test_result' ,to: 'students#test_result'
  post '/type_of_quizzes/:id/upload',to: 'type_of_quizzes#upload'
  get 'show_quiz',to: 'students#show_quiz'
  post '/student/result',to: 'students#result'


  get '/quiz/result',to: 'quiz_result#index'
  get '/quiz/:id/result',to: 'quiz_result#index'
  get '/notification/:id/result',to: 'quiz_result#show_result'


  
  # result_notification


  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :type_of_quiz
  serialize :options, Array
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token, only: %i{create update_question}
  # GET /questions or /questions.json
  require 'roo'
  require 'spreadsheet'
  def index
    @questions = Question.where(type_of_quiz_id: params[:type_of_quiz]).shuffle()
    @image_upload = ImageUpload.new
    @type_of_quiz = TypeOfQuiz.find(params[:type_of_quiz])
    @class_name = @type_of_quiz.quiz.level.module_name.class_name.name
    @module_name = @type_of_quiz.quiz.level.module_name.name
    @level_name = @type_of_quiz.quiz.level.name
    @quiz_title = @type_of_quiz.quiz.title
    @type_of_quiz_title = TypeOfQuiz.find(params[:type_of_quiz]).type.name
  end

  # GET /questions/1 or /questions/1.json
  def show
  end

  def upload
    data= ImageUpload.import(params[:upload_excel])
    # data.default_sheet = 'Sheet 3'
 
    data.each(id: 'ID', name: 'FULL_NAME') do |hash|
     puts hash.inspect
     # => { id: 1, name: 'John Smith' }
   end
  end
  # GET /questions/new
  def new
    @question = Question.new
    @type_of_quiz_name=TypeOfQuiz.find(params[:type_of_quiz]).type.name
  end

  # GET /questions/1/edit
  def edit
    @type_of_quiz_name=TypeOfQuiz.find(params[:type_of_quiz]).type.name
  end

  # POST /questions or /questions.json
  def create
    # @question = Question.new(question_params)

    # respond_to do |format|
    #   if @question.save
    #     format.html { redirect_to question_url(@question), notice: "Question was successfully created." }
    #     format.json { render :show, status: :created, location: @question }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: @question.errors, status: :unprocessable_entity }
    #   end
    # end

    question=params[:question]
    correct_answer=params[:correct_answer]
    type_of_quiz=params[:type_of_quiz]
    i=1
    options=[]
    while(!params["option#{i}"].nil?)
      options<<params["option#{i}"]
      i=i+1
    end
    Question.create({question:question,options:options,answer:correct_answer,type_of_quiz_id:type_of_quiz})
    redirect_to questions_path(type_of_quiz: params[:type_of_quiz]), notice: "Question was successfully added."
  end

  def create_question
    Question.all
  end

  # PATCH/PUT /questions/1 or /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to question_url(@question), notice: "Question was successfully updated." }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_question
    question_id=params[:question_id]
    question=params[:question]
    correct_answer=params[:correct_answer]
    type_of_quiz=params[:type_of_quiz]
    i=1
    options=[]
    while(!params["option#{i}"].nil?)
      if params["option#{i}"] != ""
        options<<params["option#{i}"]
      end
      i=i+1
    end
    question_to_update=Question.find(question_id)
    question_to_update.update(question:question,options:options,answer:correct_answer,type_of_quiz_id:type_of_quiz)
    redirect_to questions_url(type_of_quiz: params[:type_of_quiz]), notice: "Question was successfully updated."
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    @question.destroy

    respond_to do |format|
      format.html { redirect_to request.referer, notice: "Question was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:question, :options, :answer, :type_of_quiz_id, :explanation)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_question.html.erb
<div id="<%= dom_id question %>">
  <% index=@questions.find_index(question) %>
  <div class="w-full px-8 py-4">
    <div class="max-w-lg">
      <br>
      <p class="text-xl text-gray-600">
        Q<%= index+1 %>.&ensp;
        <% if TypeOfQuiz.find(params[:type_of_quiz]).type.name == "image question" || TypeOfQuiz.find(params[:type_of_quiz]).type.name == "Image question with text-field" %>
        <% ques=question.question.split('@') %>
        <%= ques[0] %>
        <% else %>
      
        <%= question.question %>

        <% end %>
      </p>
      <p>
        <% unless question.explanation.nil? %> 
          Explanation :-
          <%= question.explanation %> 
        <% end %>
      </p>
      <div class="mt-4 space-y-4 mb-6">
        <% if TypeOfQuiz.find(params[:type_of_quiz]).type.name == "Fill ups"%>
        answer: <input type="text" name="correct-answer" class="option-of-question options block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full">
        <% elsif TypeOfQuiz.find(params[:type_of_quiz]).type.name == "Jumbled Words" %>
        correct sequence : <input type="text" name="correct-answer" class="option-of-question options block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full">
        <% elsif TypeOfQuiz.find(params[:type_of_quiz]).type.name == "Mid-text-selecter" %>
        <div class="flex items-center mb-2">
          <select name="correct-answer<%= question.id %>" >
            <% question.options.each do |option| %>
                <option id="<%= index %><%=option %>" name="correct-answer<%= question.id %>" class="focus:ring-cyan-500 h-4 w-4 text-cyan-600 border-gray-300"><%= option %></option>
            <% end %>
          </select>
        </div>

        <% elsif TypeOfQuiz.find(params[:type_of_quiz]).type.name == "Select one" %>    
          <div>
            <label for="location" class="block text-sm font-medium text-gray-700">Select</label>
            <select id="location" name="correct-answer<%= question.id %>" class="mt-1 block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md">
              <% question.options.each do |option| %>
                <option id="<%= index %><%=option %>" name="correct-answer<%= question.id %>"><%= option %></option>
              <% end %>    
            </select> 
          </div>
          
         <% elsif TypeOfQuiz.find(params[:type_of_quiz]).type.name == "Mid text Selector" %>    
          <div>
            <label for="location" class="block text-sm font-medium text-gray-700">Select</label>
            <select id="location" name="correct-answer<%= question.id %>" class="mt-1 block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md">
              <% question.options.each do |option| %>
                <option id="<%= index %><%=option %>" name="correct-answer<%= question.id %>"><%= option %></option>
              <% end %>  
            </select>   
          </div>

          <% elsif TypeOfQuiz.find(params[:type_of_quiz]).type.name == "image question" %>    
          <div>
          <img src="<%= ques[1] %>" alt="image question">
          </div>
          <% question.options.each do |option| %>
           
            <div class="flex items-center mb-2">
              <input id="<%= index %><%=option %>" value="<%= option %>,<%= question.id %>" name="selected_ans<%= index+1 %>" type="radio" class="focus:ring-cyan-500 h-4 w-4 text-cyan-600 border-gray-300">
              <label for="<%= index %><%=option %>" class="ml-3 block text-sm font-medium text-gray-700"><%= option %></label>
            </div>
          <% end %>

          <% elsif TypeOfQuiz.find(params[:type_of_quiz]).type.name == "Image question with text-field" %>    
          <div>
          <img src="<%= ques[1] %>" alt="image question">
          </div>
          answer: <input type="text" name="correct-answer" class="option-of-question options block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full">

          <% elsif TypeOfQuiz.find(params[:type_of_quiz]).type.name == "Written question" %>    
         
          answer: <textarea  name="correct-answer" class="option-of-question options block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"  rows="4" cols="50" > </textarea>
          
        <% else %>
          <% question.options.each do |option| %>
            <div class="flex items-center mb-2">
              <input id="<%= index %><%=option %>" value="<%= option %>,<%= question.id %>" name="selected_ans<%= index+1 %>" type="radio" class="focus:ring-cyan-500 h-4 w-4 text-cyan-600 border-gray-300">
              <label for="<%= index %><%=option %>" class="ml-3 block text-sm font-medium text-gray-700"><%= option %></label>
            </div>
          <% end %>
        <% end %>
        <div class="w-full">
          <!-- <%= link_to 'Edit',edit_question_path(id: question.id,type_of_quiz: question.type_of_quiz.id,edit:'true',question_id: question.id), class: "float-left bg-transparent hover:bg-cyan-700 text-cyan-600 font-semibold hover:text-white py-2 px-4 border border-cyan-700 hover:border-transparent rounded" %> -->
          <%= link_to 'Delete',question_path(question, type_of_quiz:params[:type_of_quiz]),method: :delete,data: {confirm: "Are you sure"} ,class: "float-left ml-5 bg-transparent hover:bg-red-500 text-red-600 font-semibold hover:text-white py-2 px-4 border border-red-500 hover:border-transparent rounded" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/questions/edit.html.erb
<%= link_to 'Back', questions_path(type_of_quiz: params[:type_of_quiz]), class: "float-left ml-5 mt-5 bg-transparent hover:bg-green-700 text-green-800 font-semibold hover:text-white py-2 px-4 border border-cyan-700 hover:border-transparent rounded" %>
<%= render 'questions/form' %>

app/views/questions/index.html.erb
<div class="w-full mt-5 bg-white py-4 px-4">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
    <h2 class="mt-8 mb-4 px-4 text-2xl uppercase text-left leading-6 font-medium text-gray-500 sm:px-6 lg:px-8">
      <%= "#{@class_name} > #{@module_name} > #{@level_name} > #{@quiz_title} > " %>
    </h2>
    <span class="mb-2 px-4 text-3xl uppercase text-left leading-6 font-medium text-gray-500 sm:px-6 lg:px-8">
      <%= "#{@type_of_quiz_title} > "%>Questions
    </span>




  <%= form_with(model: @image_upload, class: "contents") do |form| %>
    <div class="flex justify-center mt-8">
    <div class="rounded-lg shadow-xl bg-gray-50  w-full mb-8">
        <div class="m-4">
            <label class="inline-block mb-2 text-gray-500">Upload <b><%= TypeOfQuiz.find(params[:type_of_quiz]).type.name %> </b>Question</label>
            <p class="text-gray-500">Please select file that in (.xslx) format </p>
            <%= link_to "Click here for check instruction", upload_detail_path(quiz_id: params[:type_of_quiz]),class: "text-blue-600 float-left" %>

            <div class="flex items-center justify-center w-full">
                <label
                    class="flex flex-col w-full h-32 border-4 border-blue-200 border-dashed hover:bg-gray-100 hover:border-gray-300">
                    <div class="flex flex-col items-center justify-center pt-7">
                        <svg xmlns="http://www.w3.org/2000/svg" class="w-8 h-8 text-gray-400 group-hover:text-gray-600"
                            fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12" />
                        </svg>
                        <p class="pt-1 text-sm tracking-wider text-gray-400 group-hover:text-gray-600">
                            Attach a file</p>
                    </div>
                    <%= form.file_field :upload_excel ,class: "opacity-0" , accept: ".xls,.xlsx" %>
                    <%= hidden_field_tag 'type_of_quiz', params[:type_of_quiz]  %>
                
                </label>
            </div>
        </div>
        <p class="selected_file"></p>


        <div class="flex justify-center p-2">
            <button type="button" class="upload_ques_unselected w-full px-4 py-2 text-white bg-blue-500 rounded shadow-xl cursor-not-allowed opacity-50">Upload Question</button>
            <button type="submit" class="upload_ques hidden w-full px-4 py-2 text-white bg-blue-500 rounded shadow-xl">Upload Question</button>

            </div>
    </div>
  </div> 
  <% end %>




  
  
    <div class="flex justify-between items-center w-full">
      <h1 class="font-bold text-3xl uppercase text-gray-500"><%= TypeOfQuiz.find(params[:type_of_quiz]).type.name %> questions</h1>
      <%= link_to 'Add a new question', new_question_path(type_of_quiz: params[:type_of_quiz]), class: "hidden rounded-lg py-3 px-5 bg-cyan-700 hover:bg-cyan-600 text-white block font-medium" %>
    </div>
    <% if @questions.present? %>
      <div class="pt-6 sm:pt-5">
        <div role="group" aria-labelledby="label-notifications">
          <div class="w-full">
            <div id="questions" class="min-w-full">
              <%= form_tag do%>
                <%= render @questions %>
                <button type="button" id="submit-answer-button" class="hidden float-right rounded-lg py-3 px-5 bg-cyan-700 hover:bg-green-600 text-white block font-medium">Submit</button>
                <button type="button" id="submit-answer-button" class="hidden float-right rounded-lg py-3 px-5 bg-cyan-700 hover:bg-green-600 text-white block font-medium">Back</button>
                  <%= link_to "Back", request.referer,class: "float-right rounded-lg py-3 px-5 bg-cyan-700 hover:bg-green-600 text-white block font-medium" %>
                <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<script>
  $("#submit-answer-button").on("click",function() {
    $.ajax({
      type: 'post',
      data: ("form").serialize(),
      url: "<%= create_question_path %>",
      success: function() {
        
      }
    })

  })

  $('input[type=file]').change(function(e) { 
    $(".upload_ques_unselected").addClass("hidden");
    $(".upload_ques").removeClass("hidden");

    
    var file = e.target.files[0].name;
    $('.selected_file').html('<b>'+file+'</b>'); 
});
</script>

app/views/questions/new.html.erb
<%= link_to 'Back', questions_path(type_of_quiz: params[:type_of_quiz]), class: "float-left ml-5 mt-5 bg-transparent hover:bg-green-700 text-green-800 font-semibold hover:text-white py-2 px-4 border border-cyan-700 hover:border-transparent rounded" %>
<%= render 'questions/form' %>

app/views/questions/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @question %>

    <%= link_to 'Edit this question', edit_question_path(@question), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this question', question_path(@question), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to questions', questions_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>