config/routes.rb
Rails.application.routes.draw do
  resources :managestudents

  resources :student_quizzes
  get 'all_students',to: 'student_quizzes#all_students'
  get 'assign_quiz', to: 'student_quizzes#assign_quiz'
  resources :class_names do
    resources :module_names do
      resources :levels 
    end
  end

  get 'set_module_name', to: 'students#set_module_name', :defaults => { :format => 'js' }
  get 'set_level', to: 'students#set_level', :defaults => { :format => 'js' }
  get 'set_quiz', to: 'students#set_quiz', :defaults => { :format => 'js' }
  get 'set_type_of_quiz', to: 'students#set_type_of_quiz', :defaults => { :format => 'js' }

  # resources :module_names
  # resources :levels
  # resources :class_names

  resources :image_uploads
  resources :questions
  resources :type_of_quizzes
  resources :quizzes
  get 'home', to: 'static_pages#home'
  get 'teacher', to: 'static_pages#show'

  get 'upload_detail', to: 'static_pages#upload_detail'

  get 'activate_quiz', to: 'quizzes#activate_quiz'
  
  root 'static_pages#home'
  # root 'devise/sessions#new'
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  
  
  devise_for :views
  # devise_for :users
  get 'create_question',to: 'questions#create_question'
  post 'update_question', to:"questions#update_question"
  get 'students',to: 'students#index'
  get 'test_result' ,to: 'students#test_result'
  post '/type_of_quizzes/:id/upload',to: 'type_of_quizzes#upload'
  get 'show_quiz',to: 'students#show_quiz'
  post '/student/result',to: 'students#result'


  get '/quiz/result',to: 'quiz_result#index'
  get '/quiz/:id/result',to: 'quiz_result#index'
  get '/notification/:id/result',to: 'quiz_result#show_result'


  
  # result_notification


  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    before_action :check_is_login
    before_action :set_class_name
    before_action :set_module_name,:set_level,:set_quiz,:set_type_of_quiz,only: %i[index test_result]
    before_action :set_path_name, only: %i[index test_result]
    skip_before_action :verify_authenticity_token
    @module_name 
    @level 
    @quiz
    def check_is_login
        if user_signed_in?
        else
        redirect_to user_session_path
        end
      end

    def index         
        set_module_name()
        if current_user.role == "student"
            render layout: "student"
        else
            redirect_to '/teacher'
        end
    end

    def show_quiz         
        set_module_name()
        unless StudentQuiz.where(user_id: current_user.id, class_name_id: @class_name.id).length == 0
            @questions = Question.where(type_of_quiz_id: params[:type_of_quiz]).shuffle()
            @duration = TypeOfQuiz.find(params[:type_of_quiz]).duration
        end
        render layout: "student"
    end

    def result
        @notification=Notification.create title:"test" , descriptions: "#{current_user.email} has given #{TypeOfQuiz.find(params[:type_of_quiz]).quiz.title}",user_id: current_user.id,type_id: TypeOfQuiz.find(params[:type_of_quiz]).type_id
        i=1
        @question = Question.where(type_of_quiz_id: params[:type_of_quiz])
        @question.each do |question|
            answer=params["selected_ans#{question.id}"].split(',')
            puts answer.to_json
            @quiz_res= QuizResult.new
            @quiz_res.type_id=question.type_of_quiz.type.id
            @quiz_res.question=question.question
            @quiz_res.options=question.options
            @quiz_res.correct_ans=question.answer
            @quiz_res.explanation=question.explanation
            @quiz_res.submited_ans=answer[0]
            @quiz_res.notification_id=Notification.find(@notification.id)
            @quiz_res.save
            i=i+1
        end
        redirect_to test_result_path(notification:@notification.id) 
    end 
    def test_result 
        type_name=Type.find(Notification.find(params[:notification]).type_id).name
        if type_name == "Written question"
            @message="Questions successfully submited"
        else
            quiz_result=Notification.find(params[:notification]).quiz_results    
            @score=0
            @result=Array.new   
            quiz_result.each_with_index  do |quiz,index|             
                if  quiz.correct_ans == quiz.submited_ans
                    @result << ["Q#{index+1}","Correct","#{quiz.correct_ans}",quiz.explanation]
                    @score = @score+1
                else
                    @result<<["Q#{index+1}","Incorrect","#{quiz.correct_ans}",quiz.explanation]
                end
            end
        end
        render layout: 'student'
    end

    def set_class_name
        @student_quiz=StudentQuiz.find_by_user_id(current_user.id)
        unless @student_quiz.nil?
            @class_name = @student_quiz.class_name
        end
    end
 
    def set_module_name
        unless @class_name.nil?
            @module_names = @class_name.module_names
            unless params[:module_name_id].nil?
                $module_name=ModuleName.find(params[:module_name_id])
            else
                $module_name = @class_name.module_names.first
            end
            set_path_name()
            set_level()
        else
            $module_name=nil
        end
    end

    def set_level
        unless $module_name.nil?
            @levels=$module_name.levels
            unless params[:level_id].nil?
                $level=Level.find(params[:level_id])
            else
                $level = $module_name.levels.first
            end
            set_path_name()
            set_quiz()
        end
    end

    def set_quiz
        unless $level.nil?
            @quizzes=Quiz.where(level_id: $level.id)
            unless params[:quiz_id].nil?
                $quiz=Quiz.find(params[:quiz_id])
            else            
                $quiz=Quiz.where(level_id: $level.id).first
            end
            set_path_name()
            set_type_of_quiz()
        end
    end

    ### Method for Active Quiz Option
    # def set_quiz
    #     unless $level.nil?
    #         @quizzes=Quiz.where(level_id: $level.id, active: 1)
    #         unless params[:quiz_id].nil?
    #             $quiz=Quiz.find(params[:quiz_id])
    #         else            
    #             $quiz=Quiz.where(level_id: $level.id, active: 1).first
    #         end
    #         set_path_name()
    #         set_type_of_quiz()
    #     end
    # end

    def set_type_of_quiz
        @types=Type.all
        unless $quiz.nil?
            @type_of_quiz = TypeOfQuiz.where(quiz_id: $quiz)
        else
            @type_of_quiz = nil
        end
    end

    def set_path_name
        unless $module_name.nil?
            @module_name_name = $module_name.name
        else
            @module_name_name = nil
        end
        unless @class_name.nil?
            @class_name_name = @class_name.name
        end
        unless $level.nil?
            @level_name = $level.name
        else
            @level_name = nil
        end
        unless $quiz.nil?
            @quiz_title = $quiz.title
        else
            @quiz_title = nil
        end
    end

    
end

app/helpers/students_helper.rb
module StudentsHelper
   
end

app/views/students/_type_of_quizzes.html.erb
<% unless @type_of_quiz.nil? %>
<h2 class="text-2xl px-4 leading-6 font-medium text-gray-500 uppercase mt-4 mb-4">
  Type Of Quiz
</h2>
<% path_name = "#{@class_name_name} > #{@module_name_name} > #{@level_name} > #{@quiz_title}" %>
<div class="mt-2 grid grid-cols-1 mb-10 gap-6 sm:grid-cols-2 lg:grid-cols-2">
    <!-- Card -->
      <% unless @type_of_quiz[0].questions.length == 0 %>
        <a href="<%= show_quiz_path(type_of_quiz: @type_of_quiz[0], path_name: path_name) %>"class="shadow-xl">
            <div class="bg-orange-500 opacity-80 text-center uppercase text-white h-24 py-18 overflow-hidden shadow rounded-lg">
                <div>
                <div class="flex items-center">
                    <div class="flex-shrink-0">
                    <!--    
                    <svg class="h-6 w-6 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 6l3 1m0 0l-3 9a5.002 5.002 0 006.001 0M6 7l3 9M6 7l6-2m6 2l3-1m-3 1l-3 9a5.002 5.002 0 006.001 0M18 7l3 9m-3-9l-6-2m0-2v2m0 16V5m0 16H9m3 0h3" />
                    </svg>
                    -->
                    </div>
                    <div class="ml-5 w-0 py-10 flex-1">
                    <strong>
                      <% unless @type_of_quiz[0].name.nil? ||  @type_of_quiz[0].name == "" %>
                        <%= @type_of_quiz[0].name %>
                      <% else %>
                        <%= @type_of_quiz[0].type.name %>
                      <% end %>
                    </strong>
                    <% notific= Notification.where(user_id: current_user.id , type_id: TypeOfQuiz.find(@type_of_quiz[0].id).quiz.id) %>
                    <% if notific.present? %>
                    (complited)
                    <% else %>

                    <% end %>
                    </div>
                </div>
                </div>
            </div>
        </a>        
      <% end %>
      <% unless @type_of_quiz[2].questions.length == 0 %> 
        <a href="<%= show_quiz_path(type_of_quiz: @type_of_quiz[2], path_name: path_name) %>" class="shadow-xl" >
            <div class="bg-yellow-500 opacity-80 text-center uppercase text-white h-24 py-18 overflow-hidden shadow rounded-lg">
                <div>
                <div class="flex items-center">
                    <div class="flex-shrink-0">
                    <!-- Heroicon name: outline/scale -->
                    <!--    
                    <svg class="h-6 w-6 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 6l3 1m0 0l-3 9a5.002 5.002 0 006.001 0M6 7l3 9M6 7l6-2m6 2l3-1m-3 1l-3 9a5.002 5.002 0 006.001 0M18 7l3 9m-3-9l-6-2m0-2v2m0 16V5m0 16H9m3 0h3" />
                    </svg>
                        -->
                    </div>
                    <div class="ml-5 w-0 flex-1 py-10">
                    <% unless @type_of_quiz[2].name.nil? ||  @type_of_quiz[2].name == "" %>
                        <%= @type_of_quiz[2].name %>
                    <% else %>
                        <%= @type_of_quiz[2].type.name %>
                    <% end %>
                    <% notific= Notification.where(user_id: current_user.id , type_id: TypeOfQuiz.find(@type_of_quiz[2].id).type_id) %>
                    <% if notific.present? %>
                    (complited)
                    <% else %>

                    <% end %>
                </div>
                </div>
                </div>
            </div>
        </a>
        <% end %>
        <% unless @type_of_quiz[3].questions.length == 0 %>
        <a href="<%= show_quiz_path(type_of_quiz: @type_of_quiz[3], path_name: path_name) %>" class="shadow-xl">
            <div class="bg-green-500 opacity-80 text-center uppercase text-white h-24 py-18 overflow-hidden shadow rounded-lg">
              <div>
                <div class="flex items-center">
                  <div class="flex-shrink-0">
                  <!--    
                  <svg class="h-6 w-6 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 6l3 1m0 0l-3 9a5.002 5.002 0 006.001 0M6 7l3 9M6 7l6-2m6 2l3-1m-3 1l-3 9a5.002 5.002 0 006.001 0M18 7l3 9m-3-9l-6-2m0-2v2m0 16V5m0 16H9m3 0h3" />
                  </svg>
                    -->
                  </div>
                  <div class="ml-5 w-0 flex-1 py-10">
                  <% unless @type_of_quiz[3].name.nil? ||  @type_of_quiz[3].name == "" %>
                    <%= @type_of_quiz[3].name %>
                  <% else %>
                    <%= @type_of_quiz[3].type.name %>
                  <% end %>
                  <% notific= Notification.where(user_id: current_user.id , type_id: TypeOfQuiz.find(@type_of_quiz[3].id).type_id) %>
                  <% if notific.present? %>
                    (complited)
                  <% else %>

                  <% end %>
                  </div>
                </div>
              </div>
            </div>
        </a>
        <% end %>
        <% unless @type_of_quiz[1].questions.length == 0 %>
            <!-- More items... -->

            <a href="<%= show_quiz_path(type_of_quiz: @type_of_quiz[1], path_name: path_name) %>" class="shadow-xl">
            <div class="bg-red-500 opacity-80 text-center uppercase text-white h-24 py-18 overflow-hidden shadow rounded-lg">
              <div>
                <div class="flex items-center">
                  <div class="flex-shrink-0">

                  <!--    
                  <svg class="h-6 w-6 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 6l3 1m0 0l-3 9a5.002 5.002 0 006.001 0M6 7l3 9M6 7l6-2m6 2l3-1m-3 1l-3 9a5.002 5.002 0 006.001 0M18 7l3 9m-3-9l-6-2m0-2v2m0 16V5m0 16H9m3 0h3" />
                    </svg>
                    -->
                  </div>
                  <div class="ml-5 w-0 flex-1 py-10">
                  <% unless @type_of_quiz[1].name.nil? ||  @type_of_quiz[1].name == "" %>
                    <%= @type_of_quiz[1].name %>
                  <% else %>
                    <%= @type_of_quiz[1].type.name %>
                  <% end %>
                  <% notific= Notification.where(user_id: current_user.id , type_id: TypeOfQuiz.find(@type_of_quiz[1].id).type_id) %>
                  <% if notific.present? %>
                    (complited)
                  <% else %>

                  <% end %>
                  </div>
                </div>
              </div>
            </div>
          </a>
          <% end %>
          <% unless @type_of_quiz[4].questions.length == 0 %>
            <a href="<%= show_quiz_path(type_of_quiz: @type_of_quiz[4], path_name: path_name) %>" class="shadow-xl" >
            <div class="bg-cyan-500 opacity-80 text-center uppercase text-white h-24 py-18 overflow-hidden shadow rounded-lg">
              <div>
                <div class="flex items-center">
                  <div class="flex-shrink-0">
                    <!-- Heroicon name: outline/scale -->
                    <!--    
                    <svg class="h-6 w-6 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 6l3 1m0 0l-3 9a5.002 5.002 0 006.001 0M6 7l3 9M6 7l6-2m6 2l3-1m-3 1l-3 9a5.002 5.002 0 006.001 0M18 7l3 9m-3-9l-6-2m0-2v2m0 16V5m0 16H9m3 0h3" />
                    </svg>
                      -->
                  </div>
                  <div class="ml-5 w-0 flex-1 py-10">
                  <strong><%= @type_of_quiz[4].name %></strong> 
                  <% notific= Notification.where(user_id: current_user.id , type_id: TypeOfQuiz.find(@type_of_quiz[4].id).type_id) %>
                  <% unless @type_of_quiz[4].name.nil? ||  @type_of_quiz[4].name == "" %>
                    <%= @type_of_quiz[4].name %>
                  <% else %>
                    <%= @type_of_quiz[4].type.name %>
                  <% end %>
                </div>
                </div>
              </div>
            </div>
            </a>
          <% end %>
          <% unless @type_of_quiz[5].questions.length == 0 %>

            <a href="<%= show_quiz_path(type_of_quiz: @type_of_quiz[5], path_name: path_name) %>" class="shadow-xl">

            <div class="bg-pink-500 opacity-80 text-center uppercase text-white h-24 py-18 overflow-hidden shadow rounded-lg">
              <div>
                <div class="flex items-center">
                  <div class="flex-shrink-0">
                  <!--    
                  <svg class="h-6 w-6 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 6l3 1m0 0l-3 9a5.002 5.002 0 006.001 0M6 7l3 9M6 7l6-2m6 2l3-1m-3 1l-3 9a5.002 5.002 0 006.001 0M18 7l3 9m-3-9l-6-2m0-2v2m0 16V5m0 16H9m3 0h3" />
                  </svg>
                    -->
                  </div>
                  <div class="ml-5 w-0 flex-1 py-10">
                  <% unless @type_of_quiz[5].name.nil? ||  @type_of_quiz[5].name == "" %>
                    <%= @type_of_quiz[5].name %>
                  <% else %>
                    <%= @type_of_quiz[5].type.name %>
                  <% end %>
                  <% notific= Notification.where(user_id: current_user.id , type_id: TypeOfQuiz.find(@type_of_quiz[5].id).type_id) %>
                  <% if notific.present? %>
                    (complited)
                  <% else %>

                  <% end %>
                  </div>
                </div>
              </div>
            </div>
            </a>
          <% end %>
          <% unless @type_of_quiz[6].questions.length == 0 %>

            <a href="<%= show_quiz_path(type_of_quiz: @type_of_quiz[6], path_name: path_name) %>" class="shadow-xl">
            <div class="bg-purple-500 opacity-80 text-center uppercase text-white h-24 py-18 overflow-hidden shadow rounded-lg">
              <div>
                <div class="flex items-center">
                  <div class="flex-shrink-0">
                  <!--    
                  <svg class="h-6 w-6 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 6l3 1m0 0l-3 9a5.002 5.002 0 006.001 0M6 7l3 9M6 7l6-2m6 2l3-1m-3 1l-3 9a5.002 5.002 0 006.001 0M18 7l3 9m-3-9l-6-2m0-2v2m0 16V5m0 16H9m3 0h3" />
                  </svg>
                    -->
                  </div>
                  <div class="ml-5 w-0 flex-1 py-10">
                  <% unless @type_of_quiz[6].name.nil? ||  @type_of_quiz[6].name == "" %>
                    <%= @type_of_quiz[6].name %>
                  <% else %>
                    <%= @type_of_quiz[6].type.name %>
                  <% end %>
                  <% notific= Notification.where(user_id: current_user.id , type_id: TypeOfQuiz.find(@type_of_quiz[6].id).type_id) %>
                  <% if notific.present? %>
                    (complited)
                  <% else %>

                  <% end %>
                </div>
                </div>
              </div>
            </div>
            </a>
          <% end %>
          <% unless @type_of_quiz[7].questions.length == 0 %>
            <a href="<%= show_quiz_path(type_of_quiz: @type_of_quiz[7], path_name: path_name) %>" class="shadow-xl">
            <div class="bg-green-500 opacity-80 text-center uppercase text-white h-24 py-18 overflow-hidden shadow rounded-lg">
              <div>
                <div class="flex items-center">
                  <div class="flex-shrink-0">
                
                  <!--    
                  <svg class="h-6 w-6 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 6l3 1m0 0l-3 9a5.002 5.002 0 006.001 0M6 7l3 9M6 7l6-2m6 2l3-1m-3 1l-3 9a5.002 5.002 0 006.001 0M18 7l3 9m-3-9l-6-2m0-2v2m0 16V5m0 16H9m3 0h3" />
                  </svg>
                    -->
                  </div>
                  <div class="ml-5 w-0 flex-1 py-10">
                  <% unless @type_of_quiz[7].name.nil? ||  @type_of_quiz[7].name == "" %>
                    <%= @type_of_quiz[7].name %>
                  <% else %>
                    <%= @type_of_quiz[7].type.name %>
                  <% end %>
                  <% notific= Notification.where(user_id: current_user.id , type_id: TypeOfQuiz.find(@type_of_quiz[7].id).type_id) %>
                  <% if notific.present? %>
                    (complited)
                  <% else %>

                  <% end %>
                </div>
                
                  </div>
              </div>
            </div>
            </a>     
          <% end %> 
</div>
<% else %>
    <div class="text-3xl w-full px-4 leading-6 font-medium text-gray-500 uppercase mt-4 mb-4">
        No Quiz Available
    </div>
  <% end %>    

app/views/students/index.html.erb
<div class="w-full block">
  <div class="flex-col">
  <% unless @class_name.nil? %>
  <div class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
    <h2 class="text-3xl text-center leading-6 font-medium text-gray-500 uppercase mt-4 mb-4">
      <%= "#{@class_name_name}"%>
    </h2>
    <div id="module_names">
      <%= render 'students/module_names'%>
    </div>
    <div id="levels">
      <%= render 'students/levels'%>
    </div>
    <div id="quizzes">
      <%= render 'students/quizzes'%>
    </div>
    <div id="type_of_quizzes">
      <%= render 'students/type_of_quizzes'%>
    </div>

         <% else %>
      <div class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
        <h2 class="text-4xl text-center leading-6 font-medium text-gray-500 uppercase mt-4 mb-4">No Quiz Available</h2>
      </div>
    <% end %>
      </div>
      </div>


      
  <style>
  .ml-6 {
    margin-left: 15.5rem;
}
</style>
<script>
  function set_module_name(module_name)
  {
    $.ajax({
      type: 'get',
      data: 'module_name_id='+module_name,
      url: '<%= set_module_name_path %>'
    })
  }

  function set_level(level)
  {
    $.ajax({
      type: 'get',
      data: 'level_id='+level,
      url: '<%= set_level_path %>'
    })
  }

  function set_quiz(quiz)
  {
    $.ajax({
      type: 'get',
      data: 'quiz_id='+quiz,
      url: '<%= set_quiz_path %>'
    })
  }

  //reload page
  if (!localStorage.getItem("reload")) {
      /* set reload to true and then reload the page */
      localStorage.setItem("reload", "true");
      location.reload();
  }
  /* after reloading remove "reload" from localStorage */
  else {
      localStorage.removeItem("reload");
      // localStorage.clear(); // or clear it, instead
  }
</script>

app/views/students/set_level.js.erb
$("#levels").html("<%= j (render partial: 'students/levels') %>");
$("#quizzes").html("<%= j (render partial: 'students/quizzes') %>");
$("#type_of_quizzes").html("<%= j (render partial: 'students/type_of_quizzes') %>");

app/views/students/set_quiz.js.erb
$("#quizzes").html("<%= j (render partial: 'students/quizzes') %>");
$("#type_of_quizzes").html("<%= j (render partial: 'students/type_of_quizzes') %>");

app/views/students/show_quiz.html.erb
<div class="mx-auto mt-5 bg-white py-4 px-4 ml-8 mr-8 text-gray-700 px-4 py-4">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% unless @class_name.nil? %>
    <h2 class="text-lg px-4 py-4 leading-6 font-medium text-gray-500 uppercase mt-4 mb-4">
      <%= params[:path_name] %>
    </h2>
    <div class="flex justify-between items-center w-full">
      <h1 class="font-bold text-3xl uppercase text-gray-500"><%= TypeOfQuiz.find(params[:type_of_quiz]).name %> Questions</h1>
      <%= link_to 'Add a new question', new_question_path(type_of_quiz: params[:type_of_quiz]), class: "hidden rounded-lg py-3 px-5 bg-cyan-700 hover:bg-cyan-600 text-white block font-medium" %>
      <% unless @duration.nil? %>
        <div>
              <div class="float-right">
                <span class="mr-2">Time Left</span>
                <span id="hours" class="font-bold text-xl"></span>
                <span id="mins" class="font-bold text-xl"></span>
                <span id="seconds" class="font-bold text-xl"></span>
              </div>
          </div>
        </div>  
        <script>
          var total_time=<%= @duration %>*60*1000;
          window.setTimeout(function() {
                            $(".check_result").trigger("click");
                          },total_time);
        </script>
      <% end %>  
    </div>
    <% if @questions.present? %>

      <div class="pt-6 sm:pt-5 px-6 py-4">
        <div role="group" aria-labelledby="label-notifications">  
          <div class="w-full">
            <div id="questions" class="min-w-full">
              <%= form_tag('' ,{class: 'form'}) do%>
                <% @questions.each do |question| %>
                  <%= render partial: "question", locals: {question: question} %>
                <% end %>
                <%= hidden_field_tag :type_of_quiz,params[:type_of_quiz]%>
                <button type="button" id="submit1-answer-button" class="check_result mt-8 w-full rounded-lg py-3 px-5 bg-cyan-700 hover:bg-green-600 text-white block font-medium">Submit</button>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
   No Quiz is Available
  <% end %>
</div>

<script>



  $(".check_result").on("click",function() {
      console.log('here')
    $.ajax({
      type: 'post',
      data: $("form").serialize(),
      url: '/student/result',
      success: function(data) {
        console.log('good for health')
        $('#notice_succ').html(data.message);

      }
    })

  })


  $(".fillups_options").focusout(function(){
    var id= $(this).attr("id");
    var value=$(this).val();
    $('.'+id).val(value+','+id);
    console.log(id,value);
  });

  $(".witten_question_answer").focusout(function(){
    var id= $(this).attr("id");
    var value=$(this).val();
    $('.'+id).val(value+','+id);
    console.log(id,value);
  });
</script>

<style>
.px-8 {
    padding-left: 17rem;
    padding-right: 2rem;
}
</style>

<script>
  //Timer
  startTimer();
  duration = <%= @duration %>/60;
  if(duration <= 1) 
  {
    mins = <%= @duration %>-1;
    hours=0;
  }
  else
  {
    hours=duration.toString().split(".")[0]
    mins=(<%= @duration %> - hours*60)-1
  }
  seconds=60;
  function startTimer() {
    window.setTimeout(function () {
      seconds--;
        if (seconds < 1) {
          seconds = 60;
          mins--;
        }
        if (mins < 0 ) {
          if(hours >= 1)
          {
            mins = 59;
            hours--;
          }
        }
        if (hours <= 1) {
          $("#hours").html("0" + hours + ":");
        } 
        else 
        {
          $("#hours").html(hours + ":");
        }
        if (mins < 10) {
          $("#mins").html("0" + mins + ":");
        } 
        else 
        {
          $("#mins").html(mins + ":");
        }
        if (seconds < 10) {
          $("#seconds").html("0" + seconds);
        } else {
          $("#seconds").html(seconds);
        }
        startTimer();
      }, 1000);
  };
</script>