config/routes.rb
Rails.application.routes.draw do
  resources :managestudents

  resources :student_quizzes
  get 'all_students',to: 'student_quizzes#all_students'
  get 'assign_quiz', to: 'student_quizzes#assign_quiz'
  resources :class_names do
    resources :module_names do
      resources :levels 
    end
  end

  get 'set_module_name', to: 'students#set_module_name', :defaults => { :format => 'js' }
  get 'set_level', to: 'students#set_level', :defaults => { :format => 'js' }
  get 'set_quiz', to: 'students#set_quiz', :defaults => { :format => 'js' }
  get 'set_type_of_quiz', to: 'students#set_type_of_quiz', :defaults => { :format => 'js' }

  # resources :module_names
  # resources :levels
  # resources :class_names

  resources :image_uploads
  resources :questions
  resources :type_of_quizzes
  resources :quizzes
  get 'home', to: 'static_pages#home'
  get 'teacher', to: 'static_pages#show'

  get 'upload_detail', to: 'static_pages#upload_detail'

  get 'activate_quiz', to: 'quizzes#activate_quiz'
  
  root 'static_pages#home'
  # root 'devise/sessions#new'
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  
  
  devise_for :views
  # devise_for :users
  get 'create_question',to: 'questions#create_question'
  post 'update_question', to:"questions#update_question"
  get 'students',to: 'students#index'
  get 'test_result' ,to: 'students#test_result'
  post '/type_of_quizzes/:id/upload',to: 'type_of_quizzes#upload'
  get 'show_quiz',to: 'students#show_quiz'
  post '/student/result',to: 'students#result'


  get '/quiz/result',to: 'quiz_result#index'
  get '/quiz/:id/result',to: 'quiz_result#index'
  get '/notification/:id/result',to: 'quiz_result#show_result'


  
  # result_notification


  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/class_name.rb
class ClassName < ApplicationRecord
    has_many :module_names, dependent: :destroy
    has_many :student_quizzes, dependent: :destroy
end

app/models/image_upload.rb
class ImageUpload < ApplicationRecord
    has_one_attached :upload_excel
    require 'roo-xls'

    def self.import(file)
        spreadsheet = open_spreadsheet(file)
        # header = spreadsheet.row(1)
        # data=[]
        # (2..spreadsheet.last_row).each do |i|
        #   row = Hash[[header, spreadsheet.row(i)].transpose]
        #   data << row.to_hash
        # #   product = find_by_id(row["id"]) || new
        # #   product.attributes = row.to_hash.slice(*accessible_attributes)
        # #   product.save!
        # end
      end
      
      def self.open_spreadsheet(file)
        case File.extname(file.original_filename)
        when ".csv" then Csv.new(file.path, nil, :ignore)
        when ".xls" then Excel.new(file.path, nil, :ignore)
        when ".xlsx" then Roo::Excelx.new(file.path)
        else raise "Unknown file type: #{file.original_filename}"
        end
      end
end

app/models/level.rb
class Level < ApplicationRecord
  belongs_to :module_name
  has_many :quizzes, dependent: :destroy
end

app/models/module_name.rb
class ModuleName < ApplicationRecord
  belongs_to :class_name
  has_many :levels, dependent: :destroy
end

app/models/notification.rb
class Notification < ApplicationRecord
    has_many :quiz_results, dependent: :destroy
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :type_of_quiz
  serialize :options, Array
end

app/models/quiz.rb
class Quiz < ApplicationRecord
    has_many :type_of_quizzes, dependent: :destroy
    belongs_to :level
    after_create :create_type_of_quiz

    def create_type_of_quiz()
        quiz_id=id
        data=Type.all.map{|type| [type.id,quiz_id]}
        columns=[:type_id, :quiz_id]
        TypeOfQuiz.import columns,data
    end
end

app/models/quiz_result.rb
class QuizResult < ApplicationRecord
  belongs_to :notification_id, foreign_key: :notification_id, class_name: "Notification"
  serialize :options, Array
end

app/models/student_quiz.rb
class StudentQuiz < ApplicationRecord
  belongs_to :user
  belongs_to :class_name
end

app/models/type.rb
class Type < ApplicationRecord
    has_many :type_of_quiz
    validates :name, uniqueness: true
end

app/models/type_of_quiz.rb
class TypeOfQuiz < ApplicationRecord
  belongs_to :quiz
  belongs_to :type
  has_many :questions, dependent: :destroy
  has_rich_text :description
  has_one :main_image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role:{
    teacher: "teacher",
    student: "student"
  }
  # enum role: { student: 0, admin: 1 } 

end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  before_action :set_level, only: %i[ show edit update destroy ]

  # GET /levels or /levels.json
  def index
    @levels = Level.where(module_name_id: params[:module_name_id])
      @module_name = ModuleName.find(params[:module_name_id]).name
      @class_name = ClassName.find(params[:class_name_id]).name
  end

  # GET /levels/1 or /levels/1.json
  def show
  end

  # GET /levels/new
  def new
    @level = Level.new
  end

  # GET /levels/1/edit
  def edit
  end

  # POST /levels or /levels.json
  def create
    @level = Level.new(level_params)

    respond_to do |format|
      if @level.save
        format.html { redirect_to class_name_module_name_levels_path, notice: "Level was successfully created." }
        format.json { render :show, status: :created, location: @level }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /levels/1 or /levels/1.json
  def update
    respond_to do |format|
      if @level.update(level_params)
        format.html { redirect_to  class_name_module_name_levels_path(params[:class_name_id],params[:module_name_id]), notice: "Level was successfully updated." }
        format.json { render :show, status: :ok, location: @level }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /levels/1 or /levels/1.json
  def destroy
    @level.destroy

    respond_to do |format|
      format.html { redirect_to request.referer, notice: "Level was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_level
      @level = Level.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def level_params
      params.require(:level).permit(:name, :module_name_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/image_uploads_helper.rb
module ImageUploadsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quiz_result_helper.rb
module QuizResultHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
   
end

app/views/levels/_form.html.erb
<%= form_with(model: [ClassName.find(params[:class_name_id]),ModuleName.find(params[:module_name_id]),@level]) do |form| %>
  <% if level.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(level.errors.count, "error") %> prohibited this level from being saved:</h2>

      <ul>
        <% level.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name,id:"name", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

    <%= form.hidden_field :module_name_id,value: params[:module_name_id] %>

  <div class="inline">
    <%= form.submit type: "button",class: "submit-button rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>
<script>
  $(".submit-button").on('click', function() {
    if($("#name").val() =="")
    {      
      alert("Name can't be null");
    }
    else
    {
      $(".submit-button").attr("type","submit");
    }
  })
</script>

app/views/levels/_level.html.erb
<div id="<%= dom_id level %>">
   <tr>
    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
      <%= level.name %>
    </td>

    <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
      <%= link_to 'Edit', edit_class_name_module_name_level_path(params[:class_name_id],params[:module_name_id],level),class:"inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500"%>
      <%= link_to "Details",quizzes_path(level_id: level.id),class:"inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500"%>
      <%= link_to 'Delete',[level.module_name.class_name, level.module_name, level],method: :delete,data: {confirm: "Are you sure all Quizzes under this level will also be deleted"} ,class: "inline-flex items-center bg-transparent hover:bg-red-500 text-red-600 font-semibold hover:text-white py-2 px-4 border border-red-500 hover:border-transparent rounded" %>
    </td>
  </tr>
</div>

app/views/levels/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing level</h1>

  <%= render "form", level: @level %>

  <%= link_to "Back to levels", class_name_module_name_levels_path(params[:class_name_id],params[:module_name_id]), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/levels/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

<div class="w-full block">
    <div class="flex flex-col">
        <span class="float-left mb-2 mt-8 px-4 leading-6 font-medium text-gray-500 sm:px-6 lg:px-4">
          <h2 class="text-2xl text-left uppercase"><%= "#{@class_name} > #{@module_name} >"%></h2>
          <span class="text-3xl text-left uppercase">Levels</span>
          <%= link_to 'New Level', new_class_name_module_name_level_path(params[:class_name_id],params[:module_name_id]), class: "mb-5 w-fit shadow-xl py-3 px-5 bg-cyan-700 hover:bg-cyan-500 float-right text-white block font-medium" %>
        </span>
      <div class="w-full overflow-x-auto">
        <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-4">
          <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
            <table class="min-w-full divide-y divide-gray-200">
              <thead class="bg-gray-50">
                <tr>
                  <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Name
                  </th>
                  
                  <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    
                  </th>
                </tr>
              </thead>
              <tbody class="bg-white divide-y divide-gray-200">
                <%= render @levels %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
    

app/views/levels/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New level</h1>

  <%= render "form", level: @level %>

  <%= link_to "Back to levels", class_name_module_name_levels_path(params[:class_name_id],params[:module_name_id]), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>

</div>

app/views/levels/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @level %>

    <%= link_to 'Edit this level', edit_level_path(@level), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this level', level_path(@level), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to levels', levels_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>