config/routes.rb
Rails.application.routes.draw do
  resources :managestudents

  resources :student_quizzes
  get 'all_students',to: 'student_quizzes#all_students'
  get 'assign_quiz', to: 'student_quizzes#assign_quiz'
  resources :class_names do
    resources :module_names do
      resources :levels 
    end
  end

  get 'set_module_name', to: 'students#set_module_name', :defaults => { :format => 'js' }
  get 'set_level', to: 'students#set_level', :defaults => { :format => 'js' }
  get 'set_quiz', to: 'students#set_quiz', :defaults => { :format => 'js' }
  get 'set_type_of_quiz', to: 'students#set_type_of_quiz', :defaults => { :format => 'js' }

  # resources :module_names
  # resources :levels
  # resources :class_names

  resources :image_uploads
  resources :questions
  resources :type_of_quizzes
  resources :quizzes
  get 'home', to: 'static_pages#home'
  get 'teacher', to: 'static_pages#show'

  get 'upload_detail', to: 'static_pages#upload_detail'

  get 'activate_quiz', to: 'quizzes#activate_quiz'
  
  root 'static_pages#home'
  # root 'devise/sessions#new'
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  
  
  devise_for :views
  # devise_for :users
  get 'create_question',to: 'questions#create_question'
  post 'update_question', to:"questions#update_question"
  get 'students',to: 'students#index'
  get 'test_result' ,to: 'students#test_result'
  post '/type_of_quizzes/:id/upload',to: 'type_of_quizzes#upload'
  get 'show_quiz',to: 'students#show_quiz'
  post '/student/result',to: 'students#result'


  get '/quiz/result',to: 'quiz_result#index'
  get '/quiz/:id/result',to: 'quiz_result#index'
  get '/notification/:id/result',to: 'quiz_result#show_result'


  
  # result_notification


  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/class_name.rb
class ClassName < ApplicationRecord
    has_many :module_names, dependent: :destroy
    has_many :student_quizzes, dependent: :destroy
end

app/models/image_upload.rb
class ImageUpload < ApplicationRecord
    has_one_attached :upload_excel
    require 'roo-xls'

    def self.import(file)
        spreadsheet = open_spreadsheet(file)
        # header = spreadsheet.row(1)
        # data=[]
        # (2..spreadsheet.last_row).each do |i|
        #   row = Hash[[header, spreadsheet.row(i)].transpose]
        #   data << row.to_hash
        # #   product = find_by_id(row["id"]) || new
        # #   product.attributes = row.to_hash.slice(*accessible_attributes)
        # #   product.save!
        # end
      end
      
      def self.open_spreadsheet(file)
        case File.extname(file.original_filename)
        when ".csv" then Csv.new(file.path, nil, :ignore)
        when ".xls" then Excel.new(file.path, nil, :ignore)
        when ".xlsx" then Roo::Excelx.new(file.path)
        else raise "Unknown file type: #{file.original_filename}"
        end
      end
end

app/models/level.rb
class Level < ApplicationRecord
  belongs_to :module_name
  has_many :quizzes, dependent: :destroy
end

app/models/module_name.rb
class ModuleName < ApplicationRecord
  belongs_to :class_name
  has_many :levels, dependent: :destroy
end

app/models/notification.rb
class Notification < ApplicationRecord
    has_many :quiz_results, dependent: :destroy
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :type_of_quiz
  serialize :options, Array
end

app/models/quiz.rb
class Quiz < ApplicationRecord
    has_many :type_of_quizzes, dependent: :destroy
    belongs_to :level
    after_create :create_type_of_quiz

    def create_type_of_quiz()
        quiz_id=id
        data=Type.all.map{|type| [type.id,quiz_id]}
        columns=[:type_id, :quiz_id]
        TypeOfQuiz.import columns,data
    end
end

app/models/quiz_result.rb
class QuizResult < ApplicationRecord
  belongs_to :notification_id, foreign_key: :notification_id, class_name: "Notification"
  serialize :options, Array
end

app/models/student_quiz.rb
class StudentQuiz < ApplicationRecord
  belongs_to :user
  belongs_to :class_name
end

app/models/type.rb
class Type < ApplicationRecord
    has_many :type_of_quiz
    validates :name, uniqueness: true
end

app/models/type_of_quiz.rb
class TypeOfQuiz < ApplicationRecord
  belongs_to :quiz
  belongs_to :type
  has_many :questions, dependent: :destroy
  has_rich_text :description
  has_one :main_image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role:{
    teacher: "teacher",
    student: "student"
  }
  # enum role: { student: 0, admin: 1 } 

end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/image_uploads_controller.rb
class ImageUploadsController < ApplicationController
  before_action :set_image_upload, only: %i[ show edit update destroy ]
  require 'roo'
  require 'spreadsheet'

  # GET /image_uploads or /image_uploads.json
  def index


    # @workbook = Spreadsheet.open(ImageUpload.last.upload_excel.to_file)
    
    # @worksheet = @workbook.worksheet(0)
    # abort('here')

    # sheet = Roo::Spreadsheet.open(url)
    @image_uploads = ImageUpload.all
  end

  # GET /image_uploads/1 or /image_uploads/1.json
  def show
  end

  # GET /image_uploads/new
  def new
    @image_upload = ImageUpload.new
  end

  # GET /image_uploads/1/edit
  def edit
  end

  # POST /image_uploads or /image_uploads.json
  def create
    # abort('here')
    @image_upload = ImageUpload.new(image_upload_params)

    type_name=TypeOfQuiz.find(params[:type_of_quiz]).type

    
   data= ImageUpload.import(params[:image_upload][:upload_excel])
  #  data.default_sheet = 'Sheet 3'

  question=params[:question]  

   data.each_with_index do |hash,index|
    if index != 0
      option_start=2
      if type_name.name == "image question" ||type_name.name == "Image question with text-field"
       question="#{hash[0]}@#{hash[3]}"
       option_start=3

      else
        question=hash[0]
      end
    explanation = hash[1]
    correct_answer=hash[2]
    type_of_quiz=params[:type_of_quiz]
    options=[]
    if type_name.name != "Fill ups" || type_name.name != "Jumbled Words" ||type_name.name != "Written question"

      hash.each_with_index do |optiondata,index|
        if index >=option_start
          options<<optiondata
        end
      end
    
  end

      Question.create({question:question,options:options,explanation: explanation, answer:correct_answer,type_of_quiz_id:type_of_quiz})

    end
    




    # puts hash.inspect
    # debugger
    # => { id: 1, name: 'John Smith' }
  end
  
  redirect_to type_of_quizzes_path(quiz_id: TypeOfQuiz.find(params[:type_of_quiz]).quiz_id), notice: "Question was successfully added."

  end

  # PATCH/PUT /image_uploads/1 or /image_uploads/1.json
  def update
    respond_to do |format|
      if @image_upload.update(image_upload_params)
        format.html { redirect_to image_upload_url(@image_upload), notice: "Image upload was successfully updated." }
        format.json { render :show, status: :ok, location: @image_upload }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @image_upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /image_uploads/1 or /image_uploads/1.json
  def destroy
    @image_upload.destroy

    respond_to do |format|
      format.html { redirect_to image_uploads_url, notice: "Image upload was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image_upload
      @image_upload = ImageUpload.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def image_upload_params
      params.require(:image_upload).permit(:name,:upload_excel)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/image_uploads_helper.rb
module ImageUploadsHelper
end

app/helpers/managestudent_helper.rb
module ManagestudentHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quiz_result_helper.rb
module QuizResultHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
   
end

app/views/image_uploads/_form.html.erb
<%= form_with(model: image_upload, class: "contents") do |form| %>
  <% if image_upload.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(image_upload.errors.count, "error") %> prohibited this image_upload from being saved:</h2>

      <ul>
        <% image_upload.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
  <%= form.label :upload_excel %>
  <%= form.file_field :upload_excel %>

  </div>
  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/image_uploads/_image_upload.html.erb
<div id="<%= dom_id image_upload %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= image_upload.name %>
  </p>
  <% if action_name != "show" %>
    <%= link_to "Show this image upload", image_upload, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this image upload', edit_image_upload_path(image_upload), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/image_uploads/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing image upload</h1>

  <%= render "form", image_upload: @image_upload %>

  <%= link_to "Show this image upload", @image_upload, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to image uploads", image_uploads_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/image_uploads/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Image uploads</h1>
    <%= link_to 'New image upload', new_image_upload_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="image_uploads" class="min-w-full">
    <%= render @image_uploads %>
  </div>
</div>

app/views/image_uploads/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New image upload</h1>

  <%= render "form", image_upload: @image_upload %>

  <%= link_to 'Back to image uploads', image_uploads_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/image_uploads/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
    <%= url_for(@image_upload.upload_excel) %>

    <%= render @image_upload %>

    <%= link_to 'Edit this image_upload', edit_image_upload_path(@image_upload), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this image_upload', image_upload_path(@image_upload), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to image_uploads', image_uploads_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>